## Random Forest

#### Random Forest
- 집단 학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정트리를 생성, 트리를 기반으로 다수결로 결과를 유도하는 모델

In [1]:
import pandas as pd

In [3]:
iris = pd.read_csv('../Data/iris.csv')

In [4]:
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [5]:
# Feature , Target 분리
iris_data = iris[['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']]
iris_target = iris['Name']

In [7]:
# Data 크기 확인
print(iris_data.shape)
print(iris_target.shape)

(150, 4)
(150,)

#### Train , Test 분리

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train_input, test_input, train_target, test_target = \
train_test_split(
    iris_data,
    iris_target,
    # random_state = 42
)

In [10]:
print(train_input.shape, train_target.shape)
print(test_input.shape, test_target.shape)

(112, 4) (112,)
(38, 4) (38,)

## Random Forest 로 분류

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
# 모델 생성
clf = RandomForestClassifier()

In [13]:
# 학습
clf.fit(train_input, train_target)

RandomForestClassifier()

In [17]:
# 평가
clf.score(test_input, test_target)

0.9736842105263158

-----
#### 독버섯 머신러닝
- 8124 종류의 버섯의 특징과 독의 유무로 구성되어 있는 DataSet
- 버섯의 특징을 기반으로 독 유무 판단

In [18]:
# 데이터 import
import urllib.request as req

local = '../Data/mushroom.csv'
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
req.urlretrieve(url, local)
print('OK')

OK

#### RandomForest 이용 버섯 분류

In [ ]:
import pandas as pd

mr = pd.read_csv('../Data/mushroom.csv', header=None)
# header = None 옵션 필수. 불러온 데이터의 최상위 행이 컬럼명으로 출력 될 수 있음.
mr.head()

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

- 각각의 행 = 각 버섯의 종류
- 첫번째 열 : p(독), e(식용)
- 두번째, 세번째 열 : 버섯의 머리 모양 > b(벨모양 = 종), c(원뿔), x(볼록), f(평평한), k(혹모양), s(오목)
- 네번째 열 : 버섯의 머리 색깔 > n(갈색), b(황갈색), c(연한갈색)

####  Feature Data => 알파벳 문자 한개 > 숫자로 변환
- ML, DL 에 라이브러리와 함수 사용하기 위해서는 숫자 데이터셋을 사용 하여야 한다.

----
#### 연습

In [23]:
# 알파벳 -> ASCII
ord('x')

120

In [25]:
# ASCII -> 알파벳
chr(120)

'x'

In [ ]:
# mr의 1번컬럼을 숫자로 변경
for i in mr.loc[:,1]:
    print(i, ord(i))

x 120
x 120
b 98
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
b 98
x 120
x 120
s 115
f 102
x 120
x 120
x 120
b 98
x 120
b 98
b 98
b 98
f 102
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
b 98
x 120
s 115
x 120
x 120
b 98
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
b 98
x 120
x 120
b 98
f 102
b 98
x 120
x 120
s 115
b 98
b 98
b 98
b 98
f 102
x 120
f 102
x 120
x 120
f 102
b 98
f 102
x 120
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
b 98
x 120
f 102
s 115
x 120
b 98
x 120
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
b 98
f 102
x 120
b 98
x 120
x 120
b 98
b 98
x 120
x 120
s 115
x 120
x 120
x 120
x 120
s 115
x 120
x 120
s 115
x 120
x 120
f 102
f 102
x 120
x 120
b 98
f 102
x 120
b 98
b 98
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
b 98
x 120
b 98
s 115
f 102
x 120
x 120
f 102
x 120
b 98
b 98
x 120
x 120
x 120
s 115
x 120
x 120
b 98
x 120
b 98
b 98
b 98
b 98
x 120
f 102
x 120
f 102
b 98
b 98
x 120
b 98
x 120
b 98
x 120
b 98
f 102
b 98
b 98
b 98
x 120
b 98
x 120
s 115
f 102
x 120
f 102
x 120
b 98
f 102
b 98
x 120
x 120
x 120
b 98
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
b 98
x 120
x 120
f 102
x 120
b 98
b 98
b 98
b 98
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
x 120
s 115
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
s 115
b 98
b 98
b 98
f 102
x 120
b 98
b 98
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
b 98
s 115
x 120
b 98
f 102
b 98
b 98
x 120
f 102
x 120
b 98
x 120
b 98
x 120
b 98
x 120
x 120
f 102
x 120
x 120
b 98
x 120
b 98
x 120
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
b 98
x 120
b 98
x 120
x 120
b 98
b 98
x 120
b 98
b 98
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
f 102
b 98
x 120
x 120
x 120
f 102
x 120
f 102
f 102
b 98
b 98
x 120
s 115
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
b 98
x 120
x 120
f 102
x 120
s 115
x 120
b 98
s 115
b 98
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
b 98
x 120
b 98
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
f 102
x 120
b 98
x 120
f 102
x 120
x 120
f 102
b 98
x 120
f 102
x 120
x 120
b 98
b 98
f 102
b 98
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
b 98
x 120
b 98
x 120
b 98
b 98
f 102
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
b 98
f 102
x 120
x 120
f 102
s 115
f 102
f 102
x 120
b 98
x 120
b 98
b 98
b 98
f 102
f 102
f 102
f 102
x 120
s 115
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
f 102
f 102
x 120
b 98
x 120
b 98
x 120
b 98
b 98
x 120
x 120
f 102
x 120
f 102
f 102
b 98
x 120
s 115
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
f 102
x 120
f 102
b 98
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
b 98
s 115
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
b 98
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
f 102
x 120
b 98
x 120
f 102
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
s 115
f 102
s 115
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
x 120
x 120
x 120
f 102
f 102
b 98
b 98
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
b 98
f 102
b 98
b 98
s 115
f 102
b 98
x 120
f 102
f 102
x 120
f 102
s 115
b 98
b 98
f 102
b 98
x 120
x 120
x 120
b 98
f 102
x 120
x 120
x 120
b 98
x 120
f 102
f 102
f 102
x 120
b 98
b 98
x 120
f 102
x 120
b 98
f 102
x 120
x 120
x 120
f 102
b 98
x 120
f 102
b 98
x 120
x 120
x 120
b 98
b 98
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
b 98
b 98
x 120
f 102
x 120
b 98
b 98
x 120
x 120
f 102
x 120
f 102
x 120
b 98
f 102
f 102
b 98
s 115
x 120
b 98
f 102
f 102
x 120
b 98
b 98
b 98
b 98
x 120
x 120
s 115
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
b 98
x 120
b 98
f 102
x 120
b 98
b 98
x 120
f 102
x 120
b 98
f 102
b 98
b 98
b 98
f 102
x 120
b 98
x 120
b 98
f 102
x 120
x 120
x 120
f 102
x 120
f 102
b 98
b 98
x 120
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
s 115
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
b 98
b 98
f 102
b 98
x 120
b 98
x 120
b 98
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
x 120
f 102
f 102
x 120
f 102
s 115
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
b 98
s 115
x 120
x 120
x 120
b 98
b 98
x 120
b 98
f 102
s 115
x 120
s 115
f 102
f 102
b 98
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
b 98
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
b 98
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
f 102
f 102
f 102
b 98
f 102
f 102
x 120
b 98
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
b 98
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
b 98
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
b 98
b 98
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
b 98
f 102
b 98
f 102
b 98
x 120
f 102
x 120
s 115
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
b 98
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
b 98
x 120
f 102
f 102
f 102
b 98
x 120
x 120
x 120
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
x 120
b 98
x 120
x 120
b 98
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
b 98
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
b 98
f 102
f 102
x 120
b 98
x 120
f 102
x 120
f 102
f 102
x 120
f 102
b 98
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
b 98
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
b 98
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
b 98
f 102
f 102
f 102
f 102
x 120
b 98
f 102
f 102
x 120
f 102
x 120
x 120
b 98
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
b 98
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
b 98
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
b 98
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102

In [31]:
target = []
data = []

for row_index, row in mr.iterrows():
    # print(row_index, ":", row)
    # print(row.loc[0])
    target.append(row.loc[0])
    row_data = []
    for v in row.loc[1:]:
        row_data.append(ord(v))
    
    data.append(row_data)

In [33]:
print(data[:2])

[[120, 115, 110, 116, 112, 102, 99, 110, 107, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 117], [120, 115, 121, 116, 97, 102, 99, 98, 107, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 110, 103]]

#### Data Frame 생성

In [35]:
# Target 기준
targetTemp = pd.DataFrame(target)
targetTemp.head()

   0
0  p
1  e
2  e
3  p
4  e

In [38]:
# data > dataframe / column 이름 겹치지 않게 생성
dataTemp = pd.DataFrame(data)

dataTemp.rename(columns=lambda x : x+1, inplace=True)

dataTemp.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [39]:
# 2개의 DF 합치기
mr2 = pd.concat([targetTemp, dataTemp], axis='columns')

In [40]:
mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [41]:
mr2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8124 non-null   object
 1   1       8124 non-null   int64
 2   2       8124 non-null   int64
 3   3       8124 non-null   int64
 4   4       8124 non-null   int64
 5   5       8124 non-null   int64
 6   6       8124 non-null   int64
 7   7       8124 non-null   int64
 8   8       8124 non-null   int64
 9   9       8124 non-null   int64
 10  10      8124 non-null   int64
 11  11      8124 non-null   int64
 12  12      8124 non-null   int64
 13  13      8124 non-null   int64
 14  14      8124 non-null   int64
 15  15      8124 non-null   int64
 16  16      8124 non-null   int64
 17  17      8124 non-null   int64
 18  18      8124 non-null   int64
 19  19      8124 non-null   int64
 20  20      8124 non-null   int64
 21  21      8124 non-null   int64
 22  22      8124 non-null   int64
dtypes: int64(22), object(1)
memory usage: 1.4+ MB

##### Random Forest 로 분류

In [42]:
# Train, Test 분리
train_data, test_data, train_target, test_target = \
train_test_split(
    mr2.loc[:,1:],
    mr2.loc[:,0],
    random_state = 42,
    stratify=mr2.loc[:, 0]
)

In [44]:
clf = RandomForestClassifier()
clf.fit(train_data, train_target)

print("Training : ", clf.score(train_data, train_target))
print("Test : ", clf.score(test_data, test_target))

Training :  1.0
Test :  1.0

---
#### One-Hot Encoding
- 숫자 데이터가 숫자로써의 의미가 있으면 상관 없지만, 위의 데이터는 분류를 위한 데이터이므로 숫자 크기의 의미가 없다.
- 이때 사용하는 것이 One-hot Encoding 이다.
- 연관 개념 : 희소행렬