## 특성(Feature)공학과 규제(Regularization : 정형화, 일반화, 규제)

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../Data/fish.csv")
df.head()

   length   height   width
0     8.4     2.11    1.41
1    13.7     3.53    2.00
2    15.0     3.82    2.43
3    16.2     4.59    2.63
4    17.4     4.59    2.94

In [4]:
fish_full = df.to_numpy()
fish_full[:5]

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94]])

In [5]:
df = pd.read_csv("../Data/fish_weight.csv")
df.head()

   weight
0     5.9
1    32.0
2    40.0
3    51.5
4    70.0

In [6]:
fish_weight = df.to_numpy()
fish_weight[:5]

array([[ 5.9],
       [32. ],
       [40. ],
       [51.5],
       [70. ]])

In [8]:
# Train 과 Test
from sklearn.model_selection import train_test_split

In [ ]:
train_input, test_input, train_target, test_target = \
    train_test_split(
        fish_full,
        fish_weight,
        random_state=42
    )